name: 🚀 Deploy to Server via SSH

on:
  push:
    branches:
      - main # Триггер на пуши в ветку main

jobs:
  deploy:
    name: Deploy to ostrivnoi.beget.tech
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ostrivnoi.beget.tech           # Твой домен сервера
          username: ostrivnoi_ivan             # Твой SSH-пользователь
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Секрет с приватным ключом
          port: 22                             # Стандартный SSH-порт (если на Beget так)
          script: |
            cd /home/o/ostrivnoi/dev-navipoint.ru/public_html
            git pull origin main

